Repository gravitational/teleport-plugins, pull requests merged in 2020-08, with the labels that each got.

#117 Implements Version subcommand:
  access/gitlab/main.go
  access/jira/main.go
  access/mattermost/main.go
  access/pagerduty/main.go
  access/slack/main.go
  utils/runner.go
Labels: enhancement

#118 Prettier all the READMEs
  .prettierrc
  README.md
  access/gitlab/README.md
  access/jira/README.md
  access/mattermost/README.md
  access/pagerduty/README.md
  access/slack/README.md
Labels: documentation

#105 Conteinerized manual QA plan
  Makefile
  docker/.bashrc
  docker/.env
  docker/.gitignore
  docker/.screenrc
  docker/Makefile
  docker/README.md
  docker/docker-compose.yml
  docker/etc/ssh/sshd_config
  docker/ngrok-insecure.yaml.example
  docker/plugins/Dockerfile
  docker/plugins/teleport-gitlab.toml
  docker/plugins/teleport-jira-cloud.toml
  docker/plugins/teleport-mattermost.toml
  docker/plugins/teleport-pagerduty.toml
  docker/plugins/teleport-slack.toml
  docker/sshd/etc/ssh/sshd_config
  docker/sshd/pam.d/ssh
  docker/sshd/scripts/export.sh
  docker/sshd/start.sh
  docker/teleport.env
  docker/teleport/Dockerfile
  docker/teleport/access-plugin-user-role.yaml
  docker/teleport/foo-role.yaml
  docker/teleport/teleport.yaml
Labels: enhancement

#132 Release 0.2.0
  access/gitlab/Makefile
  access/gitlab/version.go
  access/jira/Makefile
  access/jira/version.go
  access/mattermost/Makefile
  access/mattermost/version.go
  access/pagerduty/Makefile
  access/pagerduty/version.go
  access/slack/Makefile
  access/slack/version.go
Labels: release-engineering

#126 teleport-slack in notification-only mode
  access/README.md
  access/slack/README.md
  access/slack/app.go
  access/slack/bot.go
  access/slack/callback_server.go
  access/slack/config.go
  access/slack/main.go
  access/slack/slack_test.go
Labels: enhancement
