Repository gravitational/teleport-plugins, pull requests merged in 2023-09, with the labels that each got.

#902 TF: fix unset `oidc_connector.spec.max_age`
  terraform/Makefile
  terraform/test/fixtures/oidc_connector_without_max_age.tf
  terraform/test/oidc_connector_test.go
  terraform/tfschema/types_terraform.go
Labels: c-ve

#905 `event-handler`: Remove `namespace` configuration
  charts/event-handler/README.md
  charts/event-handler/templates/configmap.yaml
  charts/event-handler/tests/__snapshot__/configmap_test.yaml.snap
  charts/event-handler/values.schema.json
  charts/event-handler/values.yaml
  event-handler/README.md
  event-handler/cli.go
  event-handler/teleport_events_watcher.go
  event-handler/tpl/teleport-event-handler.toml.tpl
Labels: event-handler

#901 Don't use the same CN for all mTLS certs
  event-handler/mtls_certs.go
  event-handler/mtls_certs_test.go
Labels: event-handler

#927 Stop publishing remaining plugins to quay.io (and remove all references to)
  access/email/Makefile
  access/jira/Makefile
  access/mattermost/Makefile
  access/msteams/README.md
  access/pagerduty/Makefile
  access/slack/Makefile
  docker/Makefile
  docker/plugins/Dockerfile
  docker/teleport/Dockerfile
  event-handler/Makefile
Labels: release-engineering

#928 Update base docker images to use Debian 12 distroless `static` image
  access/Dockerfile
  event-handler/Dockerfile
  event-handler/build.assets/Dockerfile
Labels: release-engineering, security
